language: python
cache: pip
sudo: true

services:
  - redis-server

python:
  - "3.6"

install:
  - pip install tox-travis codecov

script:
  - tox

after_success:
  - codecov

before_deploy:
  - sudo apt-get update
  - sudo apt-get install -y pandoc
  - pip install pypandoc

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true